import {NextResponse} from 'next/server'
import {checkoutSchema} from '@/lib/schemas'
import {supabaseAdmin} from '@/lib/supabase/server'
const jsonOptions=(value:unknown):any[]=>Array.isArray(value)?value:[]
const lagosNow=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).reduce((o:any,p)=>({...o,[p.type]:p.value}),{})
export async function POST(req:Request){
 try{
  const db=supabaseAdmin();const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)return NextResponse.json({error:'Sign in to place an order.'},{status:401});const {data:{user},error:authError}=await db.auth.getUser(token);if(authError||!user)return NextResponse.json({error:'Sign in to place an order.'},{status:401});
  const parsed=checkoutSchema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'Please check your order and delivery details.',issues:parsed.error.flatten()},{status:400});const input=parsed.data;
  const {data:profile}=await db.from('profiles').select('full_name,phone').eq('id',user.id).maybeSingle();const ids=[...new Set(input.items.map(i=>i.productId))];const {data:products,error}=await db.from('products').select('id,name,slug,active,lead_days,product_variants(id,name,price_kobo,active),customizations(id,kind,label,options,fee_kobo,active)').in('id',ids);if(error)throw error;
  let subtotal=0;const snapshots:any[]=[];let earliestLead=0;
  for(const line of input.items){const product=products?.find(p=>p.id===line.productId);const variant=product?.product_variants?.find((v:any)=>v.id===line.variantId&&v.active);if(!product?.active||!variant)return NextResponse.json({error:'A selected cake or size is no longer available.'},{status:409});earliestLead=Math.max(earliestLead,Number(product.lead_days)||0);const choices=line.customization?.choices||{};const selected:any[]=[];let optionFees=0;
   for(const [customizationId,values] of Object.entries(choices)){const group=product.customizations?.find((c:any)=>c.id===customizationId&&c.active);if(!group||!Array.isArray(values)||values.length>(group.kind==='addon'?30:1))return NextResponse.json({error:'A selected cake option is no longer available.'},{status:409});for(const value of values){const option=group&&jsonOptions(group.options).find((o:any)=>(typeof o==='string'?o:String(o?.value??o?.name??o?.label??''))===value);if(!option)return NextResponse.json({error:'A selected cake option is no longer available.'},{status:409});const fee=Math.max(0,Number((option as any)?.fee_kobo??group.fee_kobo)||0);optionFees+=fee;selected.push({kind:group.kind,label:group.label,value:typeof option==='string'?option:String((option as any)?.label??(option as any)?.name??value),fee_kobo:fee})}}
   const base=Number(variant.price_kobo);const unit=base+optionFees;subtotal+=unit*line.quantity;snapshots.push({product_id:product.id,product_snapshot:{name:product.name,slug:product.slug},variant_snapshot:{id:variant.id,name:variant.name,price_kobo:unit,base_price_kobo:base},customization:{message:line.customization?.message||'',choices:selected},quantity:line.quantity,line_total_kobo:unit*line.quantity})
  }
  const now=lagosNow();const today=`${now.year}-${now.month}-${now.day}`;const orderDate=new Date(`${input.delivery_date}T00:00:00`);const minDate=new Date(`${today}T00:00:00`);minDate.setDate(minDate.getDate()+earliestLead);if(!Number.isFinite(orderDate.getTime())||orderDate<minDate)return NextResponse.json({error:`Please choose a delivery date at least ${earliestLead} day${earliestLead===1?'':'s'} from today.`},{status:400});
  const {data:zone}=await db.from('delivery_zones').select('id,charge_kobo').eq('state',input.state.trim()).eq('city',input.city.trim()).eq('active',true).maybeSingle();if(!zone)return NextResponse.json({error:'We do not deliver to that area yet.'},{status:400});
  const weekday=orderDate.getUTCDay();const {data:slots,error:slotError}=await db.from('delivery_slots').select('id,window_name,weekday,cutoff_time').eq('zone_id',zone.id).eq('active',true).or(`weekday.is.null,weekday.eq.${weekday}`);if(slotError)throw slotError;const current=`${now.hour}:${now.minute}:00`;const slot=slots?.find(s=>s.window_name===input.delivery_window&&(input.delivery_date!==today||!s.cutoff_time||current<s.cutoff_time));if(!slot)return NextResponse.json({error:input.delivery_date===today?'That delivery window is not available or its order cutoff has passed.':'That delivery window is not available for the selected area and date.'},{status:400});
  const total=subtotal+Number(zone.charge_kobo);const customerName=profile?.full_name||input.name;const customerEmail=user.email||input.email;const customerPhone=profile?.phone||input.phone;
  const {data:order,error:orderErr}=await db.rpc('create_speedcake_order',{buyer_id:user.id,customer_name:customerName,email:customerEmail,phone:customerPhone,address:input.address,city:input.city,state:input.state,landmark:input.landmark||'',instructions:input.instructions||'',delivery_date:input.delivery_date,delivery_window:input.delivery_window,zone_id:zone.id,delivery_charge_kobo:Number(zone.charge_kobo),total_kobo:total,items:snapshots});if(orderErr)throw orderErr;
  const secret=process.env.PAYSTACK_SECRET_KEY;if(!secret)return NextResponse.json({order_number:order.order_number,error:'Payment is not configured. Please try again later.'},{status:503});const reference=`SC-${order.order_number}-${crypto.randomUUID()}`;const response=await fetch('https://api.paystack.co/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/json'},body:JSON.stringify({email:customerEmail,amount:total,currency:'NGN',reference,callback_url:`${process.env.NEXT_PUBLIC_SITE_URL}/payment/return`,metadata:{order_id:order.id,order_number:order.order_number}})});const body=await response.json();if(!response.ok||!body.status)throw new Error('Paystack could not initialize payment');const {error:paymentError}=await db.from('payments').insert({order_id:order.id,reference,amount_kobo:total,currency:'NGN',status:'pending'});if(paymentError)throw paymentError;return NextResponse.json({authorization_url:body.data.authorization_url,order_number:order.order_number})
 }catch(e){console.error('checkout error',e);return NextResponse.json({error:'Unable to start checkout. Please try again.'},{status:500})}
}
