'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {ShoppingBag,UserRound,Menu,MapPin} from 'lucide-react'
import {supabaseBrowser} from '@/lib/supabase/browser'
import {readCart} from '@/lib/cart'
type ProductSummary={category:string}
<<<<<<< HEAD
export function StoreHeader(){const [open,setOpen]=useState(false),[count,setCount]=useState(0),[signedIn,setSignedIn]=useState(false),[categories,setCategories]=useState<string[]>([]);useEffect(()=>{const refresh=()=>setCount(readCart().reduce((n,item)=>n+item.quantity,0));refresh();window.addEventListener('speedcake-cart',refresh);let subscription:{unsubscribe:()=>void}|undefined;try{const db=supabaseBrowser();db.auth.getSession().then(({data})=>setSignedIn(!!data.session));const auth=db.auth.onAuthStateChange((_event,session)=>setSignedIn(!!session));subscription=auth.data.subscription}catch{}fetch('/api/products').then(r=>r.json()).then(d=>{const products=Array.isArray(d.products)?d.products as ProductSummary[]:[];setCategories([...new Set<string>(products.map(p=>p.category).filter(Boolean))])}).catch(()=>{});return()=>{window.removeEventListener('speedcake-cart',refresh);subscription?.unsubscribe()}},[]);const accountHref='/account';return <header className="bg-[#fff9f2]/95 sticky top-0 z-40 border-b border-[#eee4dc]"><div className="container min-h-[76px] flex items-center justify-between gap-4"><Link href="/" className="serif text-[29px] tracking-tight text-[#6f3d36]">speed cake<span className="text-[#c28d79]">.</span></Link><nav className="hidden md:flex items-center gap-7 text-[13px] text-[#403835]"><Link href="/cakes">Shop all</Link>{categories.slice(0,3).map(category=><Link key={category} href={`/cakes?category=${encodeURIComponent(category)}`}>{category}</Link>)}<Link href="/track">Track order</Link></nav><div className="flex items-center gap-5"><span className="hidden lg:flex items-center gap-1 text-xs text-[#756862]"><MapPin size={14}/>Delivery options at checkout</span><Link aria-label={signedIn?'Your account':'Sign in'} title={signedIn?'Account':'Sign in'} href={accountHref}><UserRound size={19} strokeWidth={1.6}/></Link><Link aria-label={`Cart, ${count} items`} href="/cart" className="relative"><ShoppingBag size={19} strokeWidth={1.6}/><span className="absolute -right-2 -top-2 rounded-full bg-[#6f3d36] text-white w-4 h-4 grid place-items-center text-[9px]">{count}</span></Link><button aria-label={open?'Close menu':'Open menu'} className="md:hidden" onClick={()=>setOpen(!open)}><Menu size={21}/></button></div></div>{open&&<nav className="md:hidden px-6 pb-5 grid gap-4 text-sm"><Link onClick={()=>setOpen(false)} href="/cakes">Shop all cakes</Link>{categories.map(category=><Link onClick={()=>setOpen(false)} key={category} href={`/cakes?category=${encodeURIComponent(category)}`}>{category}</Link>)}<Link onClick={()=>setOpen(false)} href="/track">Track order</Link><Link onClick={()=>setOpen(false)} href={accountHref}>{signedIn?'Your account':'Sign in'}</Link></nav>}</header>}
=======
export function StoreHeader(){const [open,setOpen]=useState(false),[count,setCount]=useState(0),[signedIn,setSignedIn]=useState(false),[categories,setCategories]=useState<string[]>([]);useEffect(()=>{const refresh=()=>setCount(readCart().reduce((n,item)=>n+item.quantity,0));refresh();window.addEventListener('speedcake-cart',refresh);let subscription:{unsubscribe:()=>void}|undefined;try{const db=supabaseBrowser();db.auth.getSession().then(({data})=>setSignedIn(!!data.session));const auth=db.auth.onAuthStateChange((_event,session)=>setSignedIn(!!session));subscription=auth.data.subscription}catch{}fetch('/api/products').then(r=>r.json()).then(d=>setCategories(Array.from(new Set((d.products||[]).map((p:ProductSummary)=>p.category).filter((category:unknown):category is string=>typeof category==='string'))) as string[])).catch(()=>{});return()=>{window.removeEventListener('speedcake-cart',refresh);subscription?.unsubscribe()}},[]);const accountHref='/account';return <header className="bg-[#fff9f2]/95 sticky top-0 z-40 border-b border-[#eee4dc]"><div className="container min-h-[76px] flex items-center justify-between gap-4"><Link href="/" className="serif text-[29px] tracking-tight text-[#6f3d36]">speed cake<span className="text-[#c28d79]">.</span></Link><nav className="hidden md:flex items-center gap-7 text-[13px] text-[#403835]"><Link href="/cakes">Shop all</Link>{categories.slice(0,3).map(category=><Link key={category} href={`/cakes?category=${encodeURIComponent(category)}`}>{category}</Link>)}<Link href="/track">Track order</Link></nav><div className="flex items-center gap-5"><span className="hidden lg:flex items-center gap-1 text-xs text-[#756862]"><MapPin size={14}/>Delivery options at checkout</span><Link aria-label={signedIn?'Your account':'Sign in'} title={signedIn?'Account':'Sign in'} href={accountHref}><UserRound size={19} strokeWidth={1.6}/></Link><Link aria-label={`Cart, ${count} items`} href="/cart" className="relative"><ShoppingBag size={19} strokeWidth={1.6}/><span className="absolute -right-2 -top-2 rounded-full bg-[#6f3d36] text-white w-4 h-4 grid place-items-center text-[9px]">{count}</span></Link><button aria-label={open?'Close menu':'Open menu'} className="md:hidden" onClick={()=>setOpen(!open)}><Menu size={21}/></button></div></div>{open&&<nav className="md:hidden px-6 pb-5 grid gap-4 text-sm"><Link onClick={()=>setOpen(false)} href="/cakes">Shop all cakes</Link>{categories.map(category=><Link onClick={()=>setOpen(false)} key={category} href={`/cakes?category=${encodeURIComponent(category)}`}>{category}</Link>)}<Link onClick={()=>setOpen(false)} href="/track">Track order</Link><Link onClick={()=>setOpen(false)} href={accountHref}>{signedIn?'Your account':'Sign in'}</Link></nav>}</header>}
>>>>>>> f876f3dfa77035772d2c4ecde55566086458da1d
